# Generated by Django 5.0.3 on 2024-03-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
