# Generated by Django 5.0.3 on 2024-03-09 14:45

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_portfoliopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=portfolio.models.Image),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='text1',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(blank=True, choices=[('Newspaper', 'Newspaper'), ('Other', 'Other')], default=None, max_length=100, null=True),
        ),
    ]
