# Generated by Django 4.2.4 on 2023-08-29 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_price',
        ),
    ]
