# Generated by Django 4.2.4 on 2023-09-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_shippingadress_shippingaddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='second_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
