# Generated by Django 4.2.4 on 2023-09-27 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_product_price_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True, validators=[django.core.validators.DecimalValidator(5, 2)]),
        ),
    ]
