# Generated by Django 4.2.4 on 2023-09-27 10:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=0, max_digits=5, null=True, validators=[django.core.validators.DecimalValidator(5, 2)])),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.length'),
        ),
    ]
