# Generated by Django 4.2.4 on 2023-09-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_product_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length',
        ),
        migrations.AddField(
            model_name='product',
            name='length_variants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
