# Generated by Django 4.2.4 on 2023-09-27 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_product_length_product_length_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length_variants',
        ),
        migrations.CreateModel(
            name='LengthVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
