# Generated by Django 4.2.4 on 2023-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_product_length_variants_lengthvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lengthvariant',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='length_variants',
            field=models.ManyToManyField(blank=True, to='store.lengthvariant'),
        ),
    ]
