# Generated by Django 4.2.4 on 2023-09-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_lengthvariant_product_product_length_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='length_variants',
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='LengthVariant',
        ),
    ]
