# Generated by Django 4.2.4 on 2023-09-27 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_productname_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productname',
            name='product_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
