# Generated by Django 4.2.4 on 2023-09-28 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_productname_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productname',
            old_name='product_name',
            new_name='name',
        ),
    ]
