# Generated by Django 4.2.4 on 2023-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='product_name',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductName',
        ),
    ]
