# Generated by Django 4.2.4 on 2023-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_productgroup_delete_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='groups', to='store.product'),
        ),
    ]
