# Generated by Django 4.2.4 on 2023-09-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_productdisplay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisplay',
            name='product',
        ),
    ]
