# Generated by Django 4.2.4 on 2023-09-30 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_rename_weigth_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdisplay',
            name='image',
        ),
    ]
