# Generated by Django 4.2.4 on 2023-10-03 08:55

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_onrequestproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='onrequestproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image),
        ),
    ]
