# Generated by Django 4.2.4 on 2023-10-23 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0050_remove_shippingaddress_order_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
