# Generated by Django 4.2.4 on 2023-10-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_alter_order_order_id_alter_order_transaction_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnRequestProduct',
        ),
    ]
