# Generated by Django 4.2.4 on 2023-10-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0054_productrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
