# Generated by Django 4.2.4 on 2023-10-30 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
            preserve_default=False,
        ),
    ]
