# Generated by Django 4.2.4 on 2023-11-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0059_product_min_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_quantity',
        ),
    ]
