# Generated by Django 4.2.4 on 2023-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0060_remove_product_min_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='request_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
