# Generated by Django 4.2.4 on 2023-11-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0061_productrequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_length',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True),
        ),
    ]
