# Generated by Django 4.2.4 on 2023-11-06 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0062_product_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('p_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.productrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
