# Generated by Django 4.2.4 on 2023-11-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0064_remove_productrequest_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
