# Generated by Django 4.2.4 on 2023-11-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0065_order_cancelled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancelled',
        ),
    ]
