# Generated by Django 4.2.4 on 2023-11-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0066_remove_order_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=9)),
                ('address', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='store.shippingaddress')),
            ],
        ),
    ]
