# Generated by Django 4.2.4 on 2023-11-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0067_invoiceinformation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvoiceInformation',
            new_name='InvoiceInfo',
        ),
    ]
