# Generated by Django 4.2.4 on 2023-11-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0069_invoiceinfo_firm_shippingaddress_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
