# Generated by Django 4.2.4 on 2023-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0073_remove_order_invoice_remove_order_is_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
