# Generated by Django 4.2.4 on 2023-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0074_alter_invoiceinfo_nip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
