# Generated by Django 4.2.4 on 2023-11-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0075_order_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='order_invoices/'),
        ),
    ]
