# Generated by Django 4.2.4 on 2023-11-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0077_order_shipping_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
    ]
