# Generated by Django 4.2.4 on 2023-11-20 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0080_order_courier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_weigth',
            new_name='full_weight',
        ),
    ]
