# Generated by Django 4.2.4 on 2023-11-26 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0082_shippingcost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingCost',
            new_name='ShippingLevels',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='courier_name',
            new_name='delivery_method',
        ),
    ]
