# Generated by Django 4.2.4 on 2023-11-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0083_rename_shippingcost_shippinglevels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippinglevels',
            name='courier_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
