# Generated by Django 4.2.4 on 2023-11-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0084_shippinglevels_courier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('conversion_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('is_base', models.BooleanField(default=False)),
            ],
        ),
    ]
