# Generated by Django 4.2.4 on 2023-12-11 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0088_country_alter_shippingaddress_country'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
        migrations.RenameModel(
            old_name='Currency',
            new_name='Currencies',
        ),
    ]
