# Generated by Django 4.2.4 on 2023-12-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0089_rename_country_countries_rename_currency_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceinfo',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.countries'),
        ),
        migrations.AddField(
            model_name='invoiceinfo',
            name='postal_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceinfo',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
