# Generated by Django 4.2.4 on 2023-12-19 12:22

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0092_alter_order_shipping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='p_request',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Product in stock.'), ('Unavailable', 'Product not in stock'), ('Catalog', 'For display only.')], default='Available', max_length=100),
        ),
        migrations.DeleteModel(
            name='ProductRequest',
        ),
        migrations.DeleteModel(
            name='RequestItem',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
