# Generated by Django 4.2.4 on 2023-12-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0093_catalogitem_remove_requestitem_p_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='short_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
