# Generated by Django 4.2.4 on 2023-12-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0094_catalogitem_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='short_description',
        ),
    ]
