# Generated by Django 4.2.4 on 2023-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0099_productdisplay_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('catalog_description', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Available', 'Product in stock.'), ('Unavailable', 'Product not in stock')], default='Available', max_length=100),
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
