# Generated by Django 4.2.4 on 2023-12-20 14:09

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0100_catalog_alter_product_status_delete_catalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image),
        ),
        migrations.AddField(
            model_name='catalog',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=store.models.Image),
        ),
    ]
