# Generated by Django 4.2.4 on 2023-12-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0104_remove_catalog_detailed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mansory_line',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_rope',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
