# Generated by Django 4.2.4 on 2023-12-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0106_productsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.productcategory'),
            preserve_default=False,
        ),
    ]
