# Generated by Django 4.2.4 on 2023-12-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0109_product_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdisplay',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
