# Generated by Django 4.2.4 on 2023-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0111_remove_product_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
