# Generated by Django 4.2.4 on 2023-12-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0112_productvariant_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Ropes', 'Ropes'), ('Strings', 'Strings'), ('Mansory Lines', 'Mansory Lines')], default='None', max_length=100, null=True),
        ),
    ]
