# Generated by Django 4.2.4 on 2023-12-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0114_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color_pl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_en',
            field=models.CharField(choices=[('Available', 'Product in stock.'), ('Unavailable', 'Product not in stock')], default='Available', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_pl',
            field=models.CharField(choices=[('Available', 'Product in stock.'), ('Unavailable', 'Product not in stock')], default='Available', max_length=100, null=True),
        ),
    ]
