# Generated by Django 4.2.4 on 2023-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0116_catalog_description_en_catalog_description_pl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_en',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Ropes', 'Ropes'), ('Strings', 'Strings'), ('Mansory Lines', 'Mansory Lines')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category_pl',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('Ropes', 'Ropes'), ('Strings', 'Strings'), ('Mansory Lines', 'Mansory Lines')], default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
