# Generated by Django 4.2.4 on 2023-12-30 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0117_product_category_en_product_category_pl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category_pl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status_pl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory_pl',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='subcategory_en',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='subcategory_pl',
        ),
    ]
