# Generated by Django 4.2.4 on 2023-12-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0118_remove_product_category_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdisplay',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productdisplay',
            name='subcategory_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='subcategory_pl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
