# Generated by Django 4.2.4 on 2024-01-03 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0121_alter_product_status_returnrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnrequest',
            old_name='created_at',
            new_name='adding_date',
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.orderitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='store.returnrequest')),
            ],
        ),
    ]
