# Generated by Django 4.2.4 on 2024-01-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0122_rename_created_at_returnrequest_adding_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='returnrequest',
            name='order_items',
        ),
        migrations.AddField(
            model_name='returnitem',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='customer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='return_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='returnrequest',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
