# Generated by Django 4.2.4 on 2024-01-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0123_remove_returnitem_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='confirmed',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
