# Generated by Django 4.2.4 on 2024-01-04 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0125_alter_returnrequest_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='return_request',
        ),
        migrations.DeleteModel(
            name='ReturnRequest',
        ),
    ]
