# Generated by Django 4.2.4 on 2024-01-04 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0126_remove_returnitem_return_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnItem',
        ),
    ]
