# Generated by Django 4.2.4 on 2024-01-05 18:03

from django.db import migrations, models
import django.utils.timezone
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0128_returnrequest_returnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnrequest',
            name='encrypted_bank_account',
            field=django_cryptography.fields.encrypt(models.CharField(default=django.utils.timezone.now, max_length=100)),
            preserve_default=False,
        ),
    ]
